### ISSUE TITLE
4th edition pg 242: "parallel" where "perpendicular" meant?

### ISSUE THREAD

**Issue by aycyang** [erich666/RealTimeRendering#2]
On page 242 of the 4th edition, in introducing cascading shadow maps, there is a sentence that goes:

> The idea is to divide the view frustum's volume into a few pieces by slicing it parallel to the view direction.

But this generated a different picture in my head than what I saw in the figure on the next page. I would have described it as slicing **perpendicular** to the view direction, not parallel.

Ultimately I understood what was meant based on the figure, but this caused me a few minutes of confusion that interrupted an otherwise smooth reading experience.

Thanks to the authors for putting together this amazing and thorough resource. I've had a wonderful time reading so far.

**Comment by erich666** [comment]
Thanks, good catch! I'll add it to the corrigenda soon.

**Comment by aycyang** [comment]
I noticed another uncaught error today: on page 265, "avoiding" should be "avoided"

Is there another place you would prefer I send corrections? I noticed there are no other issues being opened here.

**Comment by erich666** [comment]
Fixed, thanks. Right, normally don't report these here - go to http://realtimerendering.com and at the bottom of the page you'll see a link to my email address.
