### ISSUE TITLE
How to compile this on linux ubuntu?

### ISSUE THREAD

**Issue by WilliamWangPeng** [erich666/RealTimeRendering#6]
Hi dear author,  

    Could you tell me how to compile this on linux ubuntu?

thank you 
best regards  
William

**Comment by erich666** [comment]
The code is dependent on the Microsoft Windows system, so you need to use WINE to run the code. See http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html#linuxPlatformHelp

As far as compiling on Linux, I don't know, sorry.
